/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controleur.LivreControleur;
import Controleur.ReservationControleur;
import java.awt.HeadlessException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Livre;

/**
 *
 * @author khali
 */
public class EspaceReservations extends javax.swing.JFrame {

    /**
     * Creates new form EspaceReservations
     */
    public EspaceReservations() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudaint = new javax.swing.JTable();
        cmdReserver = new javax.swing.JButton();
        cmdRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 255));
        jLabel1.setText("Bibliotheque");

        tableEtudaint.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEtudaint);

        cmdReserver.setBackground(new java.awt.Color(0, 51, 204));
        cmdReserver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmdReserver.setForeground(new java.awt.Color(255, 255, 255));
        cmdReserver.setText("Reserver");
        cmdReserver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReserverActionPerformed(evt);
            }
        });

        cmdRetour.setBackground(new java.awt.Color(255, 0, 51));
        cmdRetour.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdRetour.setForeground(new java.awt.Color(255, 255, 255));
        cmdRetour.setText("Retour");
        cmdRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdRetour)
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmdReserver)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmdRetour)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(cmdReserver)))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Listing();       

    }//GEN-LAST:event_formWindowOpened

    private void cmdReserverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReserverActionPerformed
            
     try {
        int row = tableEtudaint.getSelectedRow();
        int id=Integer.parseInt(tableEtudaint.getModel().getValueAt(row, 0).toString());
        R.reserver(login.userId, id);
        Livre li=l.getById(id);
        R.addLivre(li);
        Listing();   
        JOptionPane.showMessageDialog(null,"le livre a ete reserve");
        } catch (Exception e) {
                       JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
    }//GEN-LAST:event_cmdReserverActionPerformed

    private void cmdRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRetourActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
                    public void run() {
                        new MenuUser().setVisible(true);
                    }
                });
        this.dispose();
    }//GEN-LAST:event_cmdRetourActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EspaceReservations.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdReserver;
    private javax.swing.JButton cmdRetour;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEtudaint;
    // End of variables declaration//GEN-END:variables
private LivreControleur l=new LivreControleur();
private ReservationControleur R= new ReservationControleur();
private void Listing(){
       ArrayList<Livre> tab=R.getAll(login.userId);
       DefaultTableModel dm = new DefaultTableModel(null,new String[]{"ID","ISBN","Auteur","Titre","Description"});
       dm.setNumRows(0);
       for(Livre r:tab){
           Object[] m={r.getId(),r.getIsbn(),r.getAuteur(),r.getTitre(),r.getDescription()};
           dm.addRow(m);
       }
       tableEtudaint.setModel(dm);

}

   private void found(int userId,String text) {
        ArrayList<Livre> livre;
        livre=R.search(userId,text);
        DefaultTableModel model =(DefaultTableModel)tableEtudaint.getModel();
        model.setNumRows(0);
        for(Livre a:livre){
           Object[] m={a.getId(),a.getIsbn(),a.getAuteur(),a.getTitre(),a.getDescription()};
        model.addRow(m);
    }
   }
   
}
